### ISSUE TITLE
Groups in menuBox

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-contrib-menuBox#1]
As this is now a component, theoretically we don't need groups functionality, although I'm assuming we can add multiple instances to the page? 

If this is the case, suggest adding a component header. This will provide the same functionality as groups and allow components to sit between menu items.

Requires:

https://github.com/adaptlearning/adapt-contrib-core/pull/366

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-contrib-menuBox/issues/4#issuecomment-1534481547

> I don't think there would be multiple instances of this particular plugin. This is effectively just the boxMenu behaviour, but as a component, including the grouping behaviour as standard.
> Multiple instances are much harder to configure as one would need to refer to sub-pages or sub-menus (groups) by id, or some other filter category. The standard menuBox should be easy to configure in the AAT, by just dropping it onto a page.
> [...]
