### ISSUE TITLE
menuBox JSON

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-contrib-menuBox#2]
The js is looking for a JSON object called _boxMenu - should this be unique?

Requires:

https://github.com/adaptlearning/adapt-contrib-core/pull/366

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-contrib-menuBox/blob/64a9af9ac9436ead9296e9eebe55aeaf611b8481/js/MenuBoxView.js#L41-L100

**Comment by oliverfoster** [comment]
The references in the background stuff will be removed with https://github.com/cgkineo/adapt-contrib-menuBox/issues/5, the ones in the render function just need their name changing inline with schema updates.

**Comment by oliverfoster** [comment]
done
