### ISSUE TITLE
Locking in menuBox

### ISSUE THREAD

**Issue by StuartNicholls** [cgkineo/adapt-contrib-menuBox#4]
How would be handle locking if there are multiple instances of menuBox component? 

Requires:

https://github.com/adaptlearning/adapt-contrib-core/pull/366

**Comment by oliverfoster** [comment]
I don't think there would be multiple instances of this particular plugin. This will is effectively just the boxMenu behaviour, but as a component, including the grouping behaviour as standard. 

Multiple instances are much harder to configure as one would need to refer to sub-pages or sub-menus (groups) by id, or some other filter category. The standard menuBox should be easy to configure in the AAT, by just dropping it onto a page.

More generally speaking, locking is inherited from the course structure and the AdaptModel locking functions along with the other locking attributes, to set `_isLocked` for each page/menu item, it's much less to do with how the content objects are rendered. i.e. If a content object has `_isLocked = true` render it as locked.
