### ISSUE TITLE
Do we need to support menu groups?

### ISSUE THREAD

**Issue by kirsty-hames** [cgkineo/adapt-contrib-menuBox#6]
I can see this got carried over from Boxmenu however I don't think this is needed. We typically use menu groups for two reasons: 
1.  Bespoke layouts - if you want to wrap menu items in containers to give more flexibility in the styling of menus (grid layouts).
2. Section up content.

For both instances, we can do this by using multiple `menuBox` components. Blocks give us the flexibility with the layout as well as breaking up the menu structure (grouping content).

I've yet to test the group functionality with the [Introduce Menus as Pages PR](https://github.com/adaptlearning/adapt-contrib-core/pull/366#top) as I wanted to query this before doing so. From a setup perspective, I think I would find it easier to think of `menuBox` as a component and use blocks for structure rather than enabling the group config I associate with Boxmenu. 

Using blocks to group items rather than the group config would give us more flexibility with menu design too e.g. displaying other components between menu items.

I'm not sure what the impacts are with menu locking/completion etc so this will need consideration.

**Comment by oliverfoster** [comment]
Locking: https://github.com/cgkineo/adapt-contrib-menuBox/issues/4

> I don't think there would be multiple instances of this particular plugin. This is effectively just the boxMenu behaviour, but as a component, including the grouping behaviour as standard.

> Multiple instances are much harder to configure as one would need to refer to sub-pages or sub-menus (groups) by id, or some other filter category. The standard menuBox should be easy to configure in the AAT, by just dropping it onto a page.

> More generally speaking, locking is inherited from the course structure and the AdaptModel locking functions along with the other locking attributes, to set _isLocked for each page/menu item, it's much less to do with how the content objects are rendered. i.e. If a content object has _isLocked = true render it as locked.

**Comment by kirsty-hames** [comment]
Closing as we'll need to maintain groups if we can't have multiple component instances.
